server:
  port: 8082
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce?retryWrites=false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

resilience4j:
  ratelimiter:
    instances:
      productReadLimiter:
        limitForPeriod: 500
        limitRefreshPeriod: 1s
        timeoutDuration: 100ms
  circuitbreaker:
    instances:
      externalPricingCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,circuitbreakers
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
